### ISSUE TITLE
Compiled on Linux but no putty or pterm?

### ISSUE THREAD

**Issue by wsdickerson** [oSilas/putty#1]
I downloaded putty-0.78 to install on  Rocky Linux release 9.1 (Blue Onyx) (Linux  5.14.0-162.6.1.el9_1.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Nov 18 02:06:38 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux) .

cmake .; cmake --build .; sudo cmake --build . --target install

I now have psusan, pageant, puttygen, plink, pscp and psftp in /usr/local/bin.  But I can't find pterm or putty.  They are not listed in the valid targets for the Makefile. 

What am I missing?

**Comment by Erickdrakus93** [comment]
I think you need  the next libraries gcc or some secundary dependecies of gcc or/and  libgtk-3-dev make so try to run :
 sudo apt install gcc libgtk-3-dev make.

**Comment by wsdickerson** [comment]
On Rocky Linux 9, it was gtk3-devel.x86_64. That was it - thank you.
